import "@/app/_styles/globals.css";
import PrelineScript from "./_components/PrelineScript";
import Announcement from "./_components/Announcement";
import Header from "./_components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Announcement />
        <Header />
        {children}
      </body>
      <PrelineScript />
    </html>
  );
}
